apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 3
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: jackhooper/eng110-docker-test:eng110_node_prod
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
