apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: jackhooper/eng110-docker-test:eng110_mongodb
          ports:
            - containerPort: 27017
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
          volumeMounts:
            - name: mongo-data-dir
              mountPath: /data/db
      volumes:
        - name: mongo-data-dir
          persistentVolumeClaim:
            claimName: mongodb
